export const CREATE_TIMEZONE = "CREATE_TIMEZONE";
export const CREATE_TIMEZONE_SUCCESS = "CREATE_TIMEZONE_SUCCESS";
export const CREATE_TIMEZONE_FAILURE = "CREATE_TIMEZONE_FAILURE";

export const UPDATE_TIMEZONE = "UPDATE_TIMEZONE";
export const UPDATE_TIMEZONE_SUCCESS = "UPDATE_TIMEZONE_SUCCESS";
export const UPDATE_TIMEZONE_FAILURE = "UPDATE_TIMEZONE_FAILURE";

export const DELETE_TIMEZONE = "DELETE_TIMEZONE";
export const DELETE_TIMEZONE_SUCCESS = "DELETE_TIMEZONE_SUCCESS";
export const DELETE_TIMEZONE_FAILURE = "DELETE_TIMEZONE_FAILURE";

export const FETCH_TIMEZONE = "FETCH_TIMEZONE";
export const FETCH_TIMEZONE_SUCCESS = "FETCH_TIMEZONE_SUCCESS";
export const FETCH_TIMEZONE_FAILURE = "FETCH_TIMEZONE_FAILURE";