export const FETCH_BUY_TICKET = "FETCH_BUY_TICKET";
export const FETCH_BUY_TICKET_SUCCESS = "FETCH_BUY_TICKET_SUCCESS";
export const FETCH_BUY_TICKET_FAILURE = "FETCH_BUY_TICKET_FAILURE";


export const TOTAL_COUNT = "TOTAL_COUNT";
export const TOTAL_COUNT_SUCCESS = "TOTAL_COUNT_SUCCESS";
export const TOTAL_COUNT_FAILURE = "TOTAL_COUNT_FAILURE";


export const SOLD_TICKET = "SOLD_TICKET";
export const SOLD_TICKET_SUCCESS = "SOLD_TICKET_SUCCESS";
export const SOLD_TICKET_FAILURE = "SOLD_TICKET_FAILURE";

export const WINNER_TICKET = "WINNER_TICKET";
export const WINNER_TICKET_SUCCESS = "WINNER_TICKET_SUCCESS";
export const WINNER_TICKET_FAILURE = "WINNER_TICKET_FAILURE";


