export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_USER_TRANSACTION = "FETCH_USER_TRANSACTION";
export const FETCH_USER_SUCCESS_TRANSACTION = "FETCH_USER_SUCCESS_TRANSACTION";
export const FETCH_USER_FAILURE_TRANSACTION = "FETCH_USER_FAILURE_TRANSACTION";

export const FETCH_WITHDRAWAL = "FETCH_WITHDRAWAL";
export const FETCH_WITHDRAWAL_SUCCESS = "FETCH_WITHDRAWAL_SUCCESS";
export const FETCH_WITHDRAWAL_FAILURE = "FETCH_WITHDRAWAL_FAILURE";

export const FETCH_USER_TRANSACTION_BY_ID = "FETCH_USER_TRANSACTION_BY_ID";
export const FETCH_USER_SUCCESS_TRANSACTION_BY_ID =
  "FETCH_USER_SUCCESS_TRANSACTION_BY_ID";
export const FETCH_USER_FAILURE_TRANSACTION_BY_ID =
  "FETCH_USER_FAILURE_TRANSACTION_BY_ID";

export const FETCH_USER_REFERAL = "FETCH_USER_REFERAL";
export const FETCH_USER_REFERAL_SUCCESS = "FETCH_USER_REFERAL_SUCCESS";
export const FETCH_USER_REFERAL_FAILURE = "FETCH_USER_REFERAL_FAILURE";

export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILURE = "FETCH_USER_DETAILS_FAILURE";

export const FETCH_DEPOSITS = "FETCH_DEPOSITS";
export const FETCH_DEPOSITS_SUCCESS = "FETCH_DEPOSITS_SUCCESS";
export const FETCH_DEPOSITS_FAILURE = "FETCH_DEPOSITS_FAILURE";

export const FETCH_DEPOSITS_BY_ID = "FETCH_DEPOSITS_BY_ID";
export const FETCH_DEPOSITS_BY_ID_SUCCESS = "FETCH_DEPOSITS_BY_ID_SUCCESS";
export const FETCH_DEPOSITS_BY_ID_FAILURE = "FETCH_DEPOSITS_BY_ID_FAILURE";

export const UPDATE_DEPOSIT = "UPDATE_DEPOSIT";
export const UPDATE_DEPOSIT_SUCCESS = "UPDATE_DEPOSIT_SUCCESS";
export const UPDATE_DEPOSIT_FAILURE = "FETCH_DEPOSITS_BY_ID_FAILURE";
