export const FETCH_WITHDRAWAL = "FETCH_WITHDRAWAL";
export const FETCH_WITHDRAWAL_SUCCESS = "FETCH_WITHDRAWAL_SUCCESS";
export const FETCH_WITHDRAWAL_FAILURE = "FETCH_WITHDRAWAL_FAILURE";

export const UPDATE_WITHDRAWAL = "UPDATE_WITHDRAWAL";
export const UPDATE_WITHDRAWAL_SUCCESS = "UPDATE_WITHDRAWAL_SUCCESS";
export const UPDATE_WITHDRAWAL_FAILURE = "UPDATE_WITHDRAWAL_FAILURE";

export const CREATE_WITHDRAWAL = "CREATE_WITHDRAWAL";
export const CREATE_WITHDRAWAL_SUCCESS = "CREATE_WITHDRAWAL_SUCCESS";
export const CREATE_WITHDRAWAL_FAILURE = "CREATE_WITHDRAWAL_FAILURE";

export const FETCH_USER_WITHDRAWAL = "FETCH_USER_WITHDRAWAL";
export const FETCH_USER_WITHDRAWAL_SUCCESS = "FETCH_USER_WITHDRAWAL_SUCCESS";
export const FETCH_USER_WITHDRAWAL_FAILURE = "FETCH_USER_WITHDRAWAL_FAILURE";