export const CREATE_BANK_ACCOUNT = "CREATE_BANK_ACCOUNT";
export const CREATE_BANK_ACCOUNT_SUCCESS = "CREATE_BANK_ACCOUNT_SUCCESS";
export const CREATE_BANK_ACCOUNT_FAILURE = "CREATE_BANK_ACCOUNT_FAILURE";

export const UPDATE_BANK_ACCOUNT = "UPDATE_BANK_ACCOUNT";
export const UPDATE_BANK_ACCOUNT_SUCCESS = "UPDATE_BANK_ACCOUNT_SUCCESS";
export const UPDATE_BANK_ACCOUNT_FAILURE = "UPDATE_BANK_ACCOUNT_FAILURE";

export const DELETE_BANK_ACCOUNT = "DELETE_BANK_ACCOUNT";
export const DELETE_BANK_ACCOUNT_SUCCESS = "DELETE_BANK_ACCOUNT_SUCCESS";
export const DELETE_BANK_ACCOUNT_FAILURE = "DELETE_BANK_ACCOUNT_FAILURE";

export const FETCH_BANK_ACCOUNT = "FETCH_BANK_ACCOUNT";
export const FETCH_BANK_ACCOUNT_SUCCESS = "FETCH_BANK_ACCOUNT_SUCCESS";
export const FETCH_BANK_ACCOUNT_FAILURE = "FETCH_BANK_ACCOUNT_FAILURE";

export const FETCH_BANK_ACCOUNT_BY_ID = "FETCH_BANK_ACCOUNT_BY_ID";
export const FETCH_BANK_ACCOUNT_BY_ID_SUCCESS =
  "FETCH_BANK_ACCOUNT_BY_ID_SUCCESS";
export const FETCH_BANK_ACCOUNT_BY_ID_FAILURE =
  "FETCH_BANK_ACCOUNT_BY_ID_FAILURE";
