export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const UPDATE_BALANCE_SUCCESS = "UPDATE_BALANCE_SUCCESS";
export const UPDATE_BALANCE_FAILURE = "UPDATE_BALANCEFAILURE";

export const ADD_BALANCE = "ADD_BALANCE";
export const ADD_BALANCE_SUCCESS = "ADD_BALANCE_SUCCESS";
export const ADD_BALANCE_FAILURE = "ADD_BALANCEFAILURE";

export const STAFF_LOGIN = "STAFF_LOGIN";
export const STAFF_LOGIN_SUCCESS = "STAFF_LOGIN_SUCCESS";
export const STAFF_LOGIN_FAILURE = "STAFF_LOGIN_FAILURE";

export const STAFF_LOGOUT = "STAFF_LOGOUT";

export const FETCH_ADMIN_DATA = "FETCH_ADMIN_DATA";
export const FETCH_ADMIN_DATA_SUCCESS = "FETCH_ADMIN_DATA_SUCCESS";
export const FETCH_ADMIN_DATA_FAILURE = "FETCH_ADMIN_DATA_FAILURE";

export const UPDATE_TERMS_AND_CONDITION = "UPDATE_TERMS_AND_CONDITION";
export const UPDATE_TERMS_AND_CONDITION_SUCCESS =
  "UPDATE_TERMS_AND_CONDITION_SUCCESS";
export const UPDATE_TERMS_AND_CONDITION_FAILURE =
  "UPDATE_TERMS_AND_CONDITION_FAILURE";

export const ADMIN_PASSWORD_CHANGE = "ADMIN_PASSWORD_CHANGE";
export const ADMIN_PASSWORD_CHANGE_SUCCESS = "ADMIN_PASSWORD_CHANGE_SUCCESS";
export const ADMIN_PASSWORD_CHANGE_FAILURE = "ADMIN_PASSWORD_CHANGE_FAILURE";

export const ADMIN_PASSWORD_RESET = "ADMIN_PASSWORD_RESET";
export const ADMIN_PASSWORD_RESET_SUCCESS = "ADMIN_PASSWORD_RESET_SUCCESS";
export const ADMIN_PASSWORD_RESET_FAILURE = "ADMIN_PASSWORD_RESET_FAILURE";

export const ADMIN_PASSWORD_FORGET = "ADMIN_PASSWORD_FORGET";
export const ADMIN_PASSWORD_FORGET_SUCCESS = "ADMIN_PASSWORD_FORGET_SUCCESS";
export const ADMIN_PASSWORD_FORGET_FAILURE = "ADMIN_PASSWORD_FORGET_FAILURE";
