
export const USER_LOGIN_LOGS = "USER_LOGIN_LOGS";
export const USER_LOGIN_LOGS_SUCCESS = "USER_LOGIN_LOGS_SUCCESS";
export const USER_LOGIN_LOGS_FAILURE = "USER_LOGIN_LOGS_FAILURE";

export const ALL_USER_LOGIN_LOGS = "ALL_USER_LOGIN_LOGS";
export const ALL_USER_LOGIN_LOGS_SUCCESS = "ALL_USER_LOGIN_LOGS_SUCCESS";
export const ALL_USER_LOGIN_LOGS_FAILURE = "ALL_USER_LOGIN_LOGS_FAILURE";





