export const REGISTER_2FA = "REGISTER_2FA";
export const REGISTER_2FA_SUCCESS = "REGISTER_2FA_SUCCESS";
export const REGISTER_2FA_FAILURE = "REGISTER_2FA_FAILURE";

export const VERIFY_2FA = "VERIFY_2FA";
export const VERIFY_2FA_SUCCESS = "VERIFY_2FA_SUCCESS";
export const VERIFY_2FA_FAILURE = "VERIFY_2FA_FAILURE";

export const UPDATE_2FA_STATUS = "UPDATE_2FA_STATUS";
export const UPDATE_2FA_STATUS_SUCCESS = "UPDATE_2FA_STATUS_SUCCESS";
export const UPDATE_2FA_STATUS_FAILURE = "UPDATE_2FA_STATUS_FAILURE";