export const CREATE_LOTTERY = "CREATE_LOTTERY";
export const CREATE_LOTTERY_SUCCESS = "CREATE_LOTTERY_SUCCESS";
export const CREATE_LOTTERY_FAILURE = "CREATE_LOTTERY_FAILURE";

export const UPDATE_LOTTERY = "UPDATE_LOTTERY";
export const UPDATE_LOTTERY_SUCCESS = "UPDATE_LOTTERY_SUCCESS";
export const UPDATE_LOTTERY_FAILURE = "UPDATE_LOTTERY_FAILURE";

export const DELETE_LOTTERY = "DELETE_LOTTERY";
export const DELETE_LOTTERY_SUCCESS = "DELETE_LOTTERY_SUCCESS";
export const DELETE_LOTTERY_FAILURE = "DELETE_LOTTERY_FAILURE";

export const FETCH_LOTTERY = "FETCH_LOTTERY";
export const FETCH_LOTTERY_SUCCESS = "FETCH_LOTTERY_SUCCESS";
export const FETCH_LOTTERY_FAILURE = "FETCH_LOTTERY_FAILURE";

export const FETCH_LOTTERY_EDIT = "FETCH_LOTTERY_EDIT";
export const FETCH_LOTTERY_EDIT_SUCCESS = "FETCH_LOTTERY_EDIT_SUCCESS";
export const FETCH_LOTTERY_EDIT_FAILURE = "FETCH_LOTTERY_EDIT_FAILURE";

export const FETCH_GAME_REPORT = "FETCH_GAME_REPORT";
export const FETCH_GAME_REPORT_SUCCESS = "FETCH_GAME_REPORT_SUCCESS";
export const FETCH_GAME_REPORT_FAILURE = "FETCH_GAME_REPORT_FAILURE";

export const FETCH_MANUAL_DRAW_USER = "FETCH_MANUAL_DRAW_USER";
export const FETCH_MANUAL_DRAW_USER_SUCCESS = "FETCH_MANUAL_DRAW_USER_SUCCESS";
export const FETCH_MANUAL_DRAW_USER_FAILURE = "FETCH_MANUAL_DRAW_USER_FAILURE";

export const FETCH_MANUAL_DRAW_TICKET = "FETCH_MANUAL_DRAW_TICKET";
export const FETCH_MANUAL_DRAW_TICKET_SUCCESS =
  "FETCH_MANUAL_DRAW_TICKET_SUCCESS";
export const FETCH_MANUAL_DRAW_TICKET_FAILURE =
  "FETCH_MANUAL_DRAW_TICKET_FAILURE";

export const FETCH_MANUAL_DRAW_HISTORY = "FETCH_MANUAL_DRAW_HISTORY";
export const FETCH_MANUAL_DRAW_HISTORY_SUCCESS =
  "FETCH_MANUAL_DRAW_HISTORY_SUCCESS";
export const FETCH_MANUAL_DRAW_HISTORY_FAILURE =
  "FETCH_MANUAL_DRAW_HISTORY_FAILURE";

export const UPDATE_MANUAL_DRAW = "UPDATE_MANUAL_DRAW";
export const UPDATE_MANUAL_DRAW_SUCCESS = "UPDATE_MANUAL_DRAW_SUCCESS";
export const UPDATE_MANUAL_DRAW_FAILURE = "UPDATE_MANUAL_DRAW_FAILURE";
