export const FETCH_SUPPORT_TICKET = "FETCH_SUPPORT_TICKET";
export const FETCH_SUPPORT_TICKET_SUCCESS = "FETCH_SUPPORT_TICKET_SUCCESS";
export const FETCH_SUPPORT_TICKET_FAILURE = "FETCH_SUPPORT_TICKET_FAILURE";

export const UPDATE_STATUS = "UPDATE_STATUS";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_FAILURE = "UPDATE_STATUS_FAILURE";