export const FETCH_SUPPORT_TICKET_MSG_ATTACH = "FETCH_SUPPORT_TICKET_MSG_ATTACH";
export const FETCH_SUPPORT_TICKET_MSG_ATTACH_SUCCESS = "FETCH_SUPPORT_TICKET_MSG_ATTACH_SUCCESS";
export const FETCH_SUPPORT_TICKET_MSG_ATTACH_FAILURE ="FETCH_SUPPORT_TICKET_MSG_ATTACH_FAILURE";

export const FETCH_SUPPORT_TICKET_FIRST_MSG = "FETCH_SUPPORT_TICKET_FIRST_MSG";
export const FETCH_SUPPORT_TICKET_FIRST_MSG_SUCCESS = "FETCH_SUPPORT_TICKET_FIRST_MSG_SUCCESS";
export const FETCH_SUPPORT_TICKET_FIRST_MSG_FAILURE ="FETCH_SUPPORT_TICKET_FIRST_MSG_FAILURE";

export const CREATE_SUPPORT_TICKET = "CREATE_SUPPORT_TICKET";
export const CREATE_SUPPORT_TICKET_SUCCESS = "CREATE_SUPPORT_TICKET_SUCCESS";
export const CREATE_SUPPORT_TICKET_FAILURE = "CREATE_SUPPORT_TICKET_FAILURE";

export const CREATE_SUPPORT_TICKET_ATTACH = "CREATE_SUPPORT_TICKET_ATTACH";
export const CREATE_SUPPORT_TICKET_ATTACH_SUCCESS = "CREATE_SUPPORT_TICKET_ATTACH_SUCCESS";
export const CREATE_SUPPORT_TICKET_ATTACH_FAILURE = "CREATE_SUPPORT_TICKET_ATTACH_FAILURE";

export const FETCH_SUPPORT_TICKET_MSG_ATTACH_REPLY = "FETCH_SUPPORT_TICKET_MSG_ATTACH_REPLY";
export const FETCH_SUPPORT_TICKET_MSG_ATTACH_REPLY_SUCCESS = "FETCH_SUPPORT_TICKET_MSG_ATTACH_REPLY_SUCCESS";
export const FETCH_SUPPORT_TICKET_MSG_ATTACH_REPLY_FAILURE = "FETCH_SUPPORT_TICKET_MSG_ATTACH_REPLY_FAILURE";
