export const FETCH_TICKET = "FETCH_TICKET";
export const FETCH_TICKET_SUCCESS = "FETCH_TICKET_SUCCESS";
export const FETCH_TICKET_FAILURE = "FETCH_TICKET_FAILURE";


export const FETCH_TICKET_EDIT = "FETCH_TICKET_EDIT";
export const FETCH_TICKET_EDIT_SUCCESS = "FETCH_TICKET_EDIT_SUCCESS";
export const FETCH_TICKET_EDIT_FAILURE = "FETCH_TICKET_EDIT_FAILURE";

