export const CREATE_SUBADMIN = "CREATE_SUBADMIN";
export const CREATE_SUBADMIN_SUCCESS = "CREATE_SUBADMIN_SUCCESS";
export const CREATE_SUBADMIN_FAILURE = "CREATE_SUBADMIN_FAILURE";

export const UPDATE_SUBADMIN = "UPDATE_SUBADMIN";
export const UPDATE_SUBADMIN_SUCCESS = "UPDATE_SUBADMIN_SUCCESS";
export const UPDATE_SUBADMIN_FAILURE = "UPDATE_SUBADMIN_FAILURE";

export const FETCH_SUBADMIN = "FETCH_SUBADMIN";
export const FETCH_SUBADMIN_SUCCESS = "FETCH_SUBADMIN_SUCCESS";
export const FETCH_SUBADMIN_FAILURE = "FETCH_SUBADMIN_FAILURE";

export const FETCH_SUBADMIN_BY_ID = "FETCH_SUBADMINBY_ID";
export const FETCH_SUBADMIN_BY_ID_SUCCESS = "FETCH_SUBADMIN_BY_ID_SUCCESS";
export const FETCH_SUBADMIN_BY_ID_FAILURE = "FETCH_SUBADMIN_BY_ID_FAILURE";

export const CHANGE_SUBADMIN_PASSWORD = "CHANGE_SUBADMIN_PASSWORD";
export const CHANGE_SUBADMIN_PASSWORD_SUCCESS =
  "CHANGE_SUBADMIN_PASSWORD_SUCCESS";
export const CHANGE_SUBADMIN_PASSWORD_FAILURE =
  "CHANGE_SUBADMIN_PASSWORD_FAILURE";

export const FORGET_SUBADMIN_PASSWORD = "FORGET_SUBADMIN_PASSWORD";
export const FORGET_SUBADMIN_PASSWORD_SUCCESS =
  "FORGET_SUBADMIN_PASSWORD_SUCCESS";
export const FORGET_SUBADMIN_PASSWORD_FAILURE =
  "FORGET_SUBADMIN_PASSWORD_FAILURE";

export const RESET_SUBADMIN_PASSWORD = "RESET_SUBADMIN_PASSWORD";
export const RESET_SUBADMIN_PASSWORD_SUCCESS =
  "RESET_SUBADMIN_PASSWORD_SUCCESS";
export const RESET_SUBADMIN_PASSWORD_FAILURE =
  "RESET_SUBADMIN_PASSWORD_FAILURE";
