export const CREATE_REFERAL_USER = "CREATE_REFERAL_USER";
export const CREATE_REFERAL_USER_SUCCESS = "CREATE_REFERAL_USER_SUCCESS";
export const CREATE_REFERAL_USER_FAILURE = "CREATE_REFERAL_USER_FAILURE";

export const UPDATE_REFERAL_STATUS = "UPDATE_REFERAL_STATUS";
export const UPDATE_REFERAL_STATUS_SUCCESS = "UPDATE_REFERAL_STATUS_SUCCESS";
export const UPDATE_REFERAL_STATUS_FAILURE = "UPDATE_REFERAL_STATUS_FAILURE";

export const FETCH_LEVEL_PERCENT = "FETCH_LEVEL_PERCENT";
export const FETCH_LEVEL_PERCENT_SUCCESS = "FETCH_LEVEL_PERCENT_SUCCESS";
export const FETCH_LEVEL_PERCENT_FAILURE = "FETCH_LEVEL_PERCENT_FAILURE";

export const FETCH_COMMISSION_USER = "FETCH_COMMISSION_USER";
export const FETCH_COMMISSION_USER_SUCCESS = "FETCH_COMMISSION_USER_SUCCESS";
export const FETCH_COMMISSION_USER_FAILURE = "FETCH_COMMISSION_USER_FAILURE";

export const CREATE_LOTTERY_REWARDS = "CREATE_LOTTERY_REWARDS";
export const CREATE_LOTTERY_REWARDS_SUCCESS = "CREATE_LOTTERY_REWARDS_SUCCESS";
export const CREATE_LOTTERY_REWARDS_FAILURE = "CREATE_LOTTERY_REWARDS_FAILURE";

export const UPDATE_LOTTERY_REWARDS = "UPDATE_LOTTERY_REWARDS";
export const UPDATE_LOTTERY_REWARDS_SUCCESS = "UPDATE_LOTTERY_REWARDS_SUCCESS";
export const UPDATE_LOTTERY_REWARDS_FAILURE = "UPDATE_LOTTERY_REWARDS_FAILURE";

export const FETCH_LOTTERY_REWARDS = "FETCH_LOTTERY_REWARDS";
export const FETCH_LOTTERY_REWARDS_SUCCESS = "FETCH_LOTTERY_REWARDS_SUCCESS";
export const FETCH_LOTTERY_REWARDS_FAILURE = "FETCH_LOTTERY_REWARDS_FAILURE";

export const FETCH_ALL_LOTTERY_REWARDS = "FETCH_ALL_LOTTERY_REWARDS";
export const FETCH_ALL_LOTTERY_REWARDS_SUCCESS =
  "FETCH_ALL_LOTTERY_REWARDS_SUCCESS";
export const FETCH_ALL_LOTTERY_REWARDS_FAILURE =
  "FETCH_ALL_LOTTERY_REWARDS_FAILURE";
