export const SEND_MAIL = "SEND_MAIL";
export const SEND_MAIL_SUCCESS = "SEND_MAIL_SUCCESS";
export const SEND_MAIL_FAILURE = "SEND_MAIL_FAILURE";

export const SEND_MAIL_ALL = "SEND_MAIL";
export const SEND_MAIL_ALL_SUCCESS = "SEND_MAIL_ALL_SUCCESS";
export const SEND_MAIL_ALL_FAILURE = "SEND_MAIL_ALL_FAILURE";

export const FETCH_USER_EMAIL = "FETCH_USER_EMAIL";
export const FETCH_USER_EMAIL_SUCCESS = "FETCH_USER_EMAIL_SUCCESS";
export const FETCH_USER_EMAIL_FAILURE = "FETCH_USER_EMAIL_FAILURE";
