export const SUBSCRIBER_MAIL = "SUBSCRIBER_MAIL";
export const SUBSCRIBER_MAIL_SUCCESS = "SUBSCRIBER_MAIL_SUCCESS";
export const SUBSCRIBER_MAIL_FAILURE = "SUBSCRIBER_MAIL_FAILURE";

// post---
export const CREATE_SUBSCRIBE = "CREATE_SUBSCRIBE";
export const CREATE_SUBSCRIBE_SUCCESS = "CREATE_SUBSCRIBE_SUCCESS";
export const CREATE_SUBSCRIBE_FAILURE = "CREATE_SUBSCRIBE_FAILURE";

export const CREATE_SEND_ALL_MAIL = "CREATE_SEND_ALL_MAIL";
export const CREATE_SEND_ALL_MAIL_SUCCESS = "CREATE_SEND_ALL_MAIL_SUCCESS";
export const CREATE_SEND_ALL_MAIL_FAILURE = "CREATE_SEND_ALL_MAIL_FAILURE";