export const CREATE_BANNER = "CREATE_BANNER";
export const CREATE_BANNER_SUCCESS = "CREATE_BANNER_SUCCESS";
export const CREATE_BANNER_FAILURE = "CREATE_BANNER_FAILURE";

export const UPDATE_BANNER = "UPDATE_BANNER";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_FAILURE = "UPDATE_BANNER_FAILURE";

export const FETCH_BANNER = "FETCH_BANNER";
export const FETCH_BANNER_SUCCESS = "FETCH_BANNER_SUCCESS";
export const FETCH_BANNER_FAILURE = "FETCH_BANNER_FAILURE";

export const FETCH_BANNER_BY_ID = "FETCH_BANNER_BY_ID";
export const FETCH_BANNER_BY_ID_SUCCESS = "FETCH_BANNER_BY_ID_SUCCESS";
export const FETCH_BANNER_BY_ID_FAILURE = "FETCH_BANNER_BY_ID_FAILURE";
