export const CREATE_LOTTERY_PHASE = "CREATE_LOTTERY_PHASE";
export const CREATE_LOTTERY_PHASE_SUCCESS = "CREATE_LOTTERY_PHASE_SUCCESS";
export const CREATE_LOTTERY_PHASE_FAILURE = "CREATE_LOTTERY_PHASE_FAILURE";

export const UPDATE_LOTTERY_PHASE = "UPDATE_LOTTERY_PHASE";
export const UPDATE_LOTTERY_PHASE_SUCCESS = "UPDATE_LOTTERY_PHASE_SUCCESS";
export const UPDATE_LOTTERY_PHASE_FAILURE = "UPDATE_LOTTERY_PHASE_FAILURE";

export const DELETE_LOTTERY_PHASE = "DELETE_LOTTERY_PHASE";
export const DELETE_LOTTERY_PHASE_SUCCESS = "DELETE_LOTTERY_PHASE_SUCCESS";
export const DELETE_LOTTERY_PHASE_FAILURE = "DELETE_LOTTERY_PHASE_FAILURE";

export const FETCH_LOTTERY_PHASE = "FETCH_LOTTERY_PHASE";
export const FETCH_LOTTERY_PHASE_SUCCESS = "FETCH_LOTTERY_PHASE_SUCCESS";
export const FETCH_LOTTERY_PHASE_FAILURE = "FETCH_LOTTERY_PHASE_FAILURE";