export const CREATE_SCRATCH_CARD = "CREATE_SCRATCH_CARD";
export const CREATE_SCRATCH_CARD_SUCCESS = "CREATE_SCRATCH_CARD_SUCCESS";
export const CREATE_SCRATCH_CARD_FAILURE = "CREATE_SCRATCH_CARD_FAILURE";

export const UPDATE_SCRATCH_CARD = "UPDATE_SCRATCH_CARD";
export const UPDATE_SCRATCH_CARD_SUCCESS = "UPDATE_SCRATCH_CARD_SUCCESS";
export const UPDATE_SCRATCH_CARD_FAILURE = "UPDATE_SCRATCH_CARD_FAILURE";

export const DELETE_SCRATCH_CARD = "DELETE_SCRATCH_CARD";
export const DELETE_SCRATCH_CARD_SUCCESS = "DELETE_SCRATCH_CARD_SUCCESS";
export const DELETE_SCRATCH_CARD_FAILURE = "DELETE_SCRATCH_CARD_FAILURE";

export const FETCH_SCRATCH_CARD = "FETCH_SCRATCH_CARD";
export const FETCH_SCRATCH_CARD_SUCCESS = "FETCH_SCRATCH_CARD_SUCCESS";
export const FETCH_SCRATCH_CARD_FAILURE = "FETCH_SCRATCH_CARD_FAILURE";

export const FETCH_SCRATCH_CARD_ID = "FETCH_SCRATCH_CARD_ID";
export const FETCH_SCRATCH_CARD_ID_SUCCESS = "FETCH_SCRATCH_CARD_ID_SUCCESS";
export const FETCH_SCRATCH_CARD_ID_FAILURE = "FETCH_SCRATCH_CARD_ID_FAILURE";

export const CREATE_SCRATCH_CARD_TABLE = "CREATE_SCRATCH_CARD_TABLE";
export const CREATE_SCRATCH_CARD_SUCCESS_TABLE =
  "CREATE_SCRATCH_CARD_SUCCESS_TABLE";
export const CREATE_SCRATCH_CARD_FAILURE_TABLE =
  "CREATE_SCRATCH_CARD_FAILURE_TABLE";

export const UPDATE_SCRATCH_CARD_TABLE = "UPDATE_SCRATCH_CARD_TABLE";
export const UPDATE_SCRATCH_CARD_SUCCESS_TABLE =
  "UPDATE_SCRATCH_CARD_SUCCESS_TABLE";
export const UPDATE_SCRATCH_CARD_FAILURE_TABLE =
  "UPDATE_SCRATCH_CARD_FAILURE_TABLE";

export const DELETE_SCRATCH_CARD_TABLE = "DELETE_SCRATCH_CARD_TABLE";
export const DELETE_SCRATCH_CARD_TABLE_SUCCESS =
  "DELETE_SCRATCH_CARD_TABLE_SUCCESS";
export const DELETE_SCRATCH_CARD_TABLE_FAILURE =
  "DELETE_SCRATCH_CARD_TABLE_FAILURE";

export const DELETE_SCRATCH_CARD_TABLE_RANDOM =
  "DELETE_SCRATCH_CARD_TABLE_RANDOM";
export const DELETE_SCRATCH_CARD_TABLE_RANDOM_SUCCESS =
  "DELETE_SCRATCH_CARD_TABLE_RANDOM_SUCCESS";
export const DELETE_SCRATCH_CARD_TABLE_RANDOM_FAILURE =
  "DELETE_SCRATCH_CARD_TABLE_RANDOM_FAILURE";

export const FETCH_SCRATCH_CARD_SOLD = "FETCH_SCRATCH_CARD_SOLD";
export const FETCH_SCRATCH_CARD_SOLD_SUCCESS =
  "FETCH_SCRATCH_CARD_SOLD_SUCCESS";
export const FETCH_SCRATCH_CARD_SOLD_FAILURE =
  "FETCH_SCRATCH_CARD_SOLD_FAILURE";

export const FETCH_SCRATCH_CARD_WINNER = "FETCH_SCRATCH_CARD_WINNER";
export const FETCH_SCRATCH_CARD_WINNER_SUCCESS =
  "FETCH_SCRATCH_CARD_WINNER_SUCCESS";
export const FETCH_SCRATCH_CARD_WINNER_FAILURE =
  "FETCH_SCRATCH_CARD_WINNER_FAILURE";

export const FETCH_SCRATCH_GAME_REPORT = "FETCH_SCRATCH_GAME_REPORT";
export const FETCH_SCRATCH_GAME_REPORT_SUCCESS =
  "FETCH_SCRATCH_GAME_REPORT_SUCCESS";
export const FETCH_SCRATCH_GAME_REPORT_FAILURE =
  "FETCH_SCRATCH_GAME_REPORT_FAILURE";
